### ISSUE TITLE
Make the content logical

### ISSUE THREAD

**Issue by slimemc-yt** [Ninja-2007/Eye-test#1]
Hi harsh, it's Aanshumaan, we need to remove the bla bla there and replace it with something meaningful. 😁😁😁😁😂😂😀🤭

**Comment by Harsh-7070** [comment]
Ok 😂

**Comment by Harsh-7070** [comment]
It's a testing game so it's okay to put blabla.
But anyway thanks for telling me I will surely change it :)

**Comment by Harsh-7070** [comment]
I have added some useful text so i am closing this issue :)
